# Generated by Django 3.0.9 on 2021-10-22 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='content',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_copy',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_signup_enabled',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_video',
        ),
    ]
